'use strict';
const VIEWER_BOSS_ACTIONS=[
 {id:'idle',label:'Idle / lineup',duration:3.2,loop:true,note:'CRIMSON plays the imported Idle clip. In ALL FIVE, the crew show their in-game idle motion alongside him.'},
 {id:'arrival',label:'Air arrival',duration:2.6,note:'Spawn clip, aerial descent, landing ring and dust from the game renderer.'},
 {id:'walk',label:'Walk',duration:1.6,loop:true,note:'Imported Walk loop, shown in place so every joint can be inspected.'},
 {id:'pursuit',label:'Chase / run',duration:3.0,loop:true,note:'Imported Run loop with the boss turning toward a target. The rig motion is shown in place for inspection.'},
 {id:'shield',label:'Shield defence',duration:11.5,note:'Left-hand shield deploys for 0.8s, guards for 10s, then retracts for 0.7s. Cannon fire is disabled throughout.'},
 {id:'cannon',label:'Riot cannon',duration:1.65,note:'Imported Cannon_Fire clip with the game muzzle and beam effect. The shield remains stowed.'},
 {id:'sword',label:'Sword slash',duration:1.35,note:'Imported Sword_Slash clip and the blade carried by the rig.'},
 {id:'overhead',label:'Overhead sword',duration:1.85,note:'Imported Sword_Overhead clip.'},
 {id:'slam',label:'Ground smash',duration:1.65,note:'Imported Stomp clip with the game warning and impact rings.'},
 {id:'grab',label:'Grab & throw',duration:2.3,note:'Current gameplay sequence: Sword_Slash / Guard poses plus the player lift and throw. The supplied rig has no dedicated grab clip.'},
 {id:'resurrect',label:'Resurrection',duration:3.5,note:'Defeat_Kneel and Spawn clips with the game rebuild pulse and lift.'},
 {id:'defeat',label:'Defeat / laugh',duration:4.9,note:'Defeat_Kneel followed by the Taunt clip used for the boss laugh.'}
];
const VIEWER_CREW_ACTIONS=[
 {id:'idle',label:'Idle',duration:2,loop:true}, {id:'walk',label:'Walk',duration:2,loop:true},
 {id:'run',label:'Run',duration:1.25,loop:true}, {id:'punch',label:'Punch',duration:.43},
 {id:'heavy',label:'Heavy punch',duration:.92}, {id:'kick',label:'Kick',duration:.67},
 {id:'heavyKick',label:'Heavy kick',duration:.93}, {id:'block',label:'Block',duration:2,loop:true},
 {id:'dodge',label:'Dodge',duration:.55}, {id:'grab',label:'Grab',duration:1.25},
 {id:'spin',label:'Spin rival',duration:1.6}, {id:'pickup',label:'Pick up',duration:.8},
 {id:'throw',label:'Throw prop',duration:.8}, {id:'hit',label:'Take hit',duration:.45},
 {id:'down',label:'Knockdown',duration:1.1}, {id:'getup',label:'Get up',duration:.85},
 {id:'revive',label:'Revive',duration:1.55}, {id:'laser',label:'Laser stance',duration:1.5,loop:true}
];
class BrawlModelViewer{
 constructor(){
  this.canvas=document.getElementById('viewerCanvas');this.scene=new BrawlScene(this.canvas,name=>window.BRAWL_ASSETS?.[name]||'assets/'+name);
  this.sim=new BrawlSim.Sim({selected:0,ai:false});this.subject='all';this.action='idle';this.group='gameplay';this.time=0;this.playing=true;this.speed=1;
  this.azimuth=0;this.elevation=.27;this.radius=13.6;this.minRadius=3.1;this.maxRadius=28;this.pointer=null;this.pointers=new Map();this.pinchDistance=0;this.ready=false;this.last=0;
  this.subjects=document.getElementById('subjects');this.actions=document.getElementById('actionGroups');this.timeline=document.getElementById('timeline');
  this.bind();this.makeSubjects();this.makeActions();this.resize();new ResizeObserver(()=>this.resize()).observe(this.canvas.parentElement);
  this.scene.load().then(()=>{this.ready=true;document.getElementById('loadStatus').textContent='READY';document.getElementById('loadStatus').classList.add('ready');this.makeActions();this.setAction('idle','gameplay');requestAnimationFrame(t=>this.frame(t));}).catch(e=>{document.getElementById('fatalText').textContent=e.message;document.getElementById('fatal').hidden=false;document.getElementById('loadStatus').textContent='ERROR';console.error(e);});
 }
 get isBoss(){return this.subject==='all'||this.subject==='boss';}
 get actionDef(){if(this.group==='rig')return this.scene.crimson?.asset.clips.find(c=>c.name===this.action)?.extras||{duration:2};return(this.isBoss?VIEWER_BOSS_ACTIONS:VIEWER_CREW_ACTIONS).find(a=>a.id===this.action)||{duration:2,loop:true};}
 makeSubjects(){const options=[['all','ALL FIVE',null],['boss','CRIMSON',null],...BrawlSim.NAMES.map((n,i)=>[String(i),n,window.BRAWL_ASSETS?.['head-'+(i+1)+'.png']])];this.subjects.innerHTML='';for(const[id,name,portrait]of options){const b=document.createElement('button');b.type='button';b.dataset.subject=id;b.className=(id==='boss'?'boss ':id==='all'?'all ':'')+(this.subject===id?'active':'');if(portrait){const img=document.createElement('img');img.src=portrait;img.alt='';b.append(img);}b.append(document.createTextNode(name));this.subjects.append(b);}}
 makeActions(){this.actions.innerHTML='';const add=(title,entries,group)=>{const wrap=document.createElement('div');wrap.className='action-group';const h=document.createElement('h2');h.textContent=title;wrap.append(h);const grid=document.createElement('div');grid.className='action-buttons';for(const item of entries){const b=document.createElement('button');b.type='button';b.dataset.action=item.id||item.name;b.dataset.group=group;b.className=this.action===b.dataset.action&&this.group===group?'active':'';b.textContent=item.label||item.name;if(group==='rig'){const small=document.createElement('small');small.textContent=`${item.extras.duration.toFixed(2)}s · RIG CLIP`;b.append(small);}grid.append(b);}wrap.append(grid);this.actions.append(wrap);};
  if(this.isBoss){add('GAMEPLAY SEQUENCES',VIEWER_BOSS_ACTIONS,'gameplay');if(this.scene.crimson){const details=document.createElement('details');details.className='action-group';details.open=this.group==='rig';const summary=document.createElement('summary');summary.textContent=`ALL ${this.scene.crimson.asset.clips.length} IMPORTED RIG CLIPS`;details.append(summary);const grid=document.createElement('div');grid.className='action-buttons';for(const clip of this.scene.crimson.asset.clips){const b=document.createElement('button');b.type='button';b.dataset.action=clip.name;b.dataset.group='rig';b.className=this.group==='rig'&&this.action===clip.name?'active':'';b.textContent=clip.name.replaceAll('_',' ');const small=document.createElement('small');small.textContent=`${clip.extras.duration.toFixed(2)}s · RIG CLIP`;b.append(small);grid.append(b);}details.append(grid);this.actions.append(details);}document.getElementById('actionCount').textContent=this.scene.crimson?`${VIEWER_BOSS_ACTIONS.length} SEQUENCES + ${this.scene.crimson.asset.clips.length} CLIPS`:'LOADING CLIPS';}
  else{add('IN-GAME CREW MOTION',VIEWER_CREW_ACTIONS,'gameplay');document.getElementById('actionCount').textContent=`${VIEWER_CREW_ACTIONS.length} ACTIONS`;}
 }
 defaultRadius(){return this.subject==='all'?(this.canvas.clientWidth/this.canvas.clientHeight<.95?18.2:13.6):this.subject==='boss'?(this.canvas.clientWidth/this.canvas.clientHeight<.95?9.5:8.3):5.5;}
 setSubject(subject){this.subject=subject;this.group='gameplay';this.action='idle';this.time=0;this.playing=true;this.azimuth=0;this.elevation=.27;this.radius=this.defaultRadius();this.makeSubjects();this.makeActions();this.updateLabels();}
 setAction(action,group){this.action=action;this.group=group;this.time=0;this.playing=true;if(!this.isBoss&&['grab','spin'].includes(action))this.radius=Math.max(this.radius,7.2);if(this.isBoss&&['sword','overhead','Sword_Slash','Sword_Overhead'].includes(action))this.radius=Math.max(this.radius,this.canvas.clientWidth<this.canvas.clientHeight?10.8:10);this.makeActions();this.updateLabels();}
 updateLabels(){const def=this.actionDef,duration=def.duration||2;document.getElementById('playPause').textContent=this.playing?'Ⅱ PAUSE':'▶ PLAY';document.getElementById('stageActor').textContent=this.subject==='all'?'CRIMSON + CREW':this.subject==='boss'?'CRIMSON':BrawlSim.NAMES[Number(this.subject)].toUpperCase();document.getElementById('stageAction').textContent=this.group==='rig'?this.action.replaceAll('_',' ').toUpperCase():this.action.toUpperCase();document.getElementById('actionNote').textContent=this.group==='rig'?'Imported animation track with the game wrist and shield attachment corrections. In-place playback; orbit to inspect the joints.':def.note||(this.action==='run'?'The in-game walk cycle played at running cadence, shown in place.':'Procedural motion from the live game renderer.');document.getElementById('timeLabel').textContent=`${this.time.toFixed(2)} / ${duration.toFixed(2)} s`;this.timeline.max=String(Math.round(duration*1000));this.timeline.value=String(Math.round(Math.min(this.time,duration)*1000));}
 resize(){const r=this.canvas.parentElement.getBoundingClientRect();if(r.width>0&&r.height>0){this.scene.resize(Math.round(r.width),Math.round(r.height));if(this.subject==='all')this.radius=this.defaultRadius();}}
 bind(){this.subjects.addEventListener('click',e=>{const b=e.target.closest('[data-subject]');if(b)this.setSubject(b.dataset.subject);});this.actions.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)this.setAction(b.dataset.action,b.dataset.group);});document.getElementById('playPause').onclick=()=>{this.playing=!this.playing;this.updateLabels();};document.getElementById('replay').onclick=()=>{this.time=0;this.playing=true;this.updateLabels();};this.timeline.oninput=()=>{this.time=Number(this.timeline.value)/1000;this.playing=false;this.updateLabels();this.render();};document.getElementById('speed').onchange=e=>{this.speed=Number(e.target.value);};document.querySelector('.camera-row').onclick=e=>{const b=e.target.closest('[data-view]');if(!b)return;const view=b.dataset.view;this.azimuth=view==='side'?Math.PI/2:view==='back'?Math.PI:0;this.elevation=view==='reset'?.27:this.elevation;if(view==='reset')this.radius=this.defaultRadius();this.render();};
  this.canvas.addEventListener('pointerdown',e=>{this.canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);});this.canvas.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;const old=this.pointers.get(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(this.pointers.size===1){this.azimuth-=(e.clientX-old[0])*.008;this.elevation=Math.max(-.05,Math.min(1.15,this.elevation+(e.clientY-old[1])*.006));}else if(this.pointers.size===2){const pts=[...this.pointers.values()],distance=Math.hypot(pts[0][0]-pts[1][0],pts[0][1]-pts[1][1]);if(this.pinchDistance)this.radius=Math.max(this.minRadius,Math.min(this.maxRadius,this.radius*this.pinchDistance/distance));this.pinchDistance=distance;}this.render();});const release=e=>{this.pointers.delete(e.pointerId);this.pinchDistance=0;};this.canvas.addEventListener('pointerup',release);this.canvas.addEventListener('pointercancel',release);this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.radius=Math.max(this.minRadius,Math.min(this.maxRadius,this.radius*Math.exp(e.deltaY*.001)));this.render();},{passive:false});
 }
 frame(stamp){const dt=this.last?Math.min(.08,(stamp-this.last)/1000):0;this.last=stamp;if(this.playing){const def=this.actionDef,d=def.duration||2;this.time+=dt*this.speed;if(this.time>=d){if(def.loop)this.time%=d;else{this.time=d;this.playing=false;}}}this.updateLabels();this.render();requestAnimationFrame(t=>this.frame(t));}
 bossPose(){const t=this.time,a=this.action,raw=this.group==='rig';const b={x:0,z:this.subject==='all'?-2.2:0,y:0,yaw:Math.PI,phase:'battle',age:t,attack:'idle',attackAge:0,attackSerial:0,shieldPhase:'stowed',shieldAge:0,shieldHitVisual:0,hitVisual:0,visualHitSerial:0,moving:0,viewerClip:'Idle',viewerTime:t};
  if(raw){const def=this.actionDef;b.viewerClip=a;b.viewerTime=def.loop?t%(def.duration||1):Math.min(t,def.duration||0);return b;}
  if(a==='arrival'){b.phase='arrival';b.viewerClip='Spawn';b.viewerTime=Math.min(t,2.1);}
  else if(a==='walk'){b.viewerClip='Walk';b.viewerTime=t%1.6;b.moving=1;}
  else if(a==='pursuit'){b.viewerClip='Run';b.viewerTime=t%1;b.moving=1;b.yaw=Math.PI+Math.sin(t*.8)*.4;}
  else if(a==='shield'){b.viewerClip='Guard';b.viewerTime=t%2.4;if(t<.8){b.shieldPhase='deploy';b.shieldAge=t;}else if(t<10.8){b.shieldPhase='active';b.shieldAge=t-.8;}else{b.shieldPhase='retract';b.shieldAge=t-10.8;}}
  else if(a==='cannon'){b.viewerClip='Cannon_Fire';b.attack=t<.85?'charge':'beam';b.attackAge=t;}
  else if(a==='sword'||a==='overhead'){b.viewerClip=a==='sword'?'Sword_Slash':'Sword_Overhead';}
  else if(a==='slam'){b.viewerClip='Stomp';b.attack=t<.90?'slamWind':'slamImpact';b.attackAge=t<.90?t:t-.90;}
  else if(a==='grab'){b.viewerClip=t<1.2?'Sword_Slash':'Guard';b.viewerTime=t<1.2?t:t-1.2;}
  else if(a==='resurrect'){b.phase='resurrect';b.viewerClip=t<1.3?'Defeat_Kneel':'Spawn';b.viewerTime=t<1.3?Math.min(2.6,t*2):Math.min(2.1,(t-1.3)*.95);}
  else if(a==='defeat'){b.phase=t<2.6?'dead':'laugh';b.viewerClip=t<2.6?'Defeat_Kneel':'Taunt';b.viewerTime=t<2.6?t:t-2.6;}
  else{b.viewerTime=t%3.2;}return b;
 }
 fighterPose(id,x,z){const f={...this.sim.newFighter(id),x,z,yaw:0};const a=this.action,t=this.time;f.age=t;f.walk=0;f.speed=0;if(this.subject==='all'){f.walk=t*1.2;return f;}if(a==='walk'||a==='run'){f.state='walk';f.speed=a==='run'?4:2.2;f.walk=t*(a==='run'?8.5:4.2);}else if(['punch','heavy','kick','heavyKick','dodge','hit','down','getup','pickup','throw'].includes(a)){f.state=a;f.duration=this.actionDef.duration;}else if(a==='block'){f.blocking=true;}else if(a==='grab'){f.state='grabbing';}else if(a==='spin'){f.state='spin';}else if(a==='revive'){f.state=t<.65?'getup':'idle';f.duration=.65;f.age=t<.65?t:0;}else if(a==='laser'){f.state='idle';}return f;}
 render(){if(!this.ready)return;const S=this.scene,R=S.R,M=S.mesh,T=S.texture;const soloCrew=!this.isBoss,swordView=this.isBoss&&['sword','overhead','Sword_Slash','Sword_Overhead'].includes(this.action),focusY=this.subject==='all'?2.0:swordView?3.6:this.subject==='boss'?2.75:1.3,focusX=this.isBoss&&this.canvas.clientWidth/this.canvas.clientHeight<.95?.15:0;const target=[focusX,focusY,0],ce=Math.cos(this.elevation);const eye=[focusX+Math.sin(this.azimuth)*ce*this.radius,focusY+Math.sin(this.elevation)*this.radius,Math.cos(this.azimuth)*ce*this.radius];S.renderState='viewer';S.time=this.time;S.visualDt=0;R.begin(eye,target,49);R.draw(M.ground,M4.id(),{texture:T.concrete});R.draw(M.ring,M4.trs([0,.025,0],[Math.PI/2,0,0],[this.subject==='all'?4.5:this.subject==='boss'?2.6:1.35,this.subject==='all'?4.5:this.subject==='boss'?2.6:1.35,.018]),{tint:rgb('#e8d487'),unlit:true,alpha:.8,blend:true,depthWrite:false});
  const boss=this.isBoss?this.bossPose():null;let fighters=[];if(this.subject==='all'){const xs=[-3.6,-1.2,1.2,3.6];fighters=this.sim.fighters.map((_,i)=>this.fighterPose(i,xs[i],2.7));this.sim.boss=boss;this.sim.selected=-1;}else if(soloCrew){const id=Number(this.subject);fighters=[this.fighterPose(id,0,0)];this.sim.boss=this.action==='laser'?{phase:'battle'}:null;this.sim.selected=id;if(['grab','spin'].includes(this.action)){const partner=this.fighterPose((id+1)%4,1.25,.65);partner.state='grabbed';partner.yaw=Math.PI;if(this.action==='spin'){const a=this.time*8;partner.x=Math.sin(a)*1.45;partner.z=Math.cos(a)*1.45;}fighters.push(partner);}}else{this.sim.boss=boss;this.sim.selected=-1;if(this.action==='grab'){const victim=this.fighterPose(1,1.9,1);if(this.time>=.55&&this.time<1.35){victim.state='bossGrabbed';victim.x=.85;victim.z=1.25;victim.y=.55+(this.time-.55)*1.3;}else if(this.time>=1.35){victim.state='bossThrown';const flight=this.time-1.35;victim.x=.85+flight*5.5;victim.z=1.25+flight*2;victim.y=Math.max(0,1.55+flight*1.5-4.7*flight*flight);}fighters=[victim];}}
  for(const f of fighters)S.drawFighter(f,this.sim);if(soloCrew&&['pickup','throw'].includes(this.action)){const t=this.time,p=this.action==='pickup'?[.72,Math.min(1.25,.2+t*1.7),.7]:[.72+t*5,1.3+Math.sin(Math.min(1,t/.8)*Math.PI)*.65,.7+t*2];R.draw(M.props.toolbox,M4.trs(p,[t*1.2,0,t*.6],[.72,.72,.72]));}if(boss)S.drawBoss(boss);if(boss&&this.action==='cannon'&&this.group==='gameplay'&&this.time>.88&&this.time<1.40){const p=S.bossMuzzle||[1,2,1];S.drawBeam(p,[p[0]+.2,p[1]-.15,p[2]+7],.12,'#ff7d38',.9);}if(soloCrew&&this.action==='laser'&&this.time%1.5<.22)S.drawBeam([.6,1.45,.55],[.6,1.45,5],.035,'#90efff',.7);
  document.getElementById('renderStat').textContent=`${R.draws} DRAWS · ${Math.round(R.tris/1000)}K TRIANGLES`;window.__brawlViewer={subject:this.subject,action:this.action,group:this.group,time:this.time,playing:this.playing,boss:boss?{clip:boss.viewerClip,shieldPhase:boss.shieldPhase,attack:boss.attack}:null,draws:R.draws,triangles:R.tris,radius:this.radius,azimuth:this.azimuth};
 }
}
window.addEventListener('DOMContentLoaded',()=>{window.brawlModelViewer=new BrawlModelViewer();});
