const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),i=process.argv.indexOf('--baseline-ref'),ref=i<0?'dc169d4':process.argv[i+1];
const baseline=execFileSync('git',['show',ref+':brawl.html'],{cwd:root,maxBuffer:64*1024*1024});
const out=path.join(root,'.qa-run','boss-crew-health');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),report=[];
try{for(const [device,viewport,mobile] of [['desktop',{width:1280,height:800},false],['mobile-emulation',{width:430,height:932},true]])for(const label of ['before','after']){
 const c=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,serviceWorkers:'block'});
 await c.route('**/brawl.html',r=>r.fulfill({body:label==='before'?baseline:fs.readFileSync(path.join(root,'brawl.html')),contentType:'text/html'}));
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(String(e)));const start=Date.now();await p.goto('http://127.0.0.1:5174/brawl.html');await p.waitForFunction(()=>window.brawl?.state==='menu',null,{timeout:90000});const loadMs=Date.now()-start;
 await p.evaluate(()=>{brawl.start({instant:true,ai:false,seed:7391,selected:0,mode:'score'});brawl.audio.muted=true;brawl.testFrozen=true;const s=brawl.sim;s.beginBoss(0);for(let i=0;i<290;i++){s.step(1/60);brawl.scene.render(s,1/60,'playing');}Object.assign(s.boss,{x:0,z:-.7,phase:'battle',attack:'idle',moving:0,shieldPhase:'stowed'});[[-5.2,2],[-5.2,3.8],[5.2,2],[5.2,3.8]].forEach(([x,z],id)=>Object.assign(s.fighters[id],{x,z,y:0,state:'idle',speed:0,hp:100}));brawl.events();brawl.scene.effects=[];brawl.scene.camera=null;});
 const metrics=await p.evaluate(()=>new Promise(resolve=>{let last=null;const frames=[],cpu=[];const tick=t=>{if(last!==null)frames.push(t-last);last=t;const start=performance.now();brawl.scene.render(brawl.sim,1/60,'playing');cpu.push(performance.now()-start);if(cpu.length<180)return requestAnimationFrame(tick);const summary=a=>{const s=a.slice(20).sort((x,y)=>x-y);return{p95:s[Math.floor(s.length*.95)],max:s.at(-1),over33:s.filter(n=>n>33.3).length};};const R=brawl.scene.R,g=R.gl,ext=g.getExtension('WEBGL_debug_renderer_info');resolve({raf:summary(frames),renderCpu:summary(cpu),draws:R.draws,triangles:R.tris,heap:performance.memory?.usedJSHeapSize,pixelRatio:R.pixelRatio,gpu:ext?g.getParameter(ext.UNMASKED_RENDERER_WEBGL):g.getParameter(g.RENDERER)});};requestAnimationFrame(tick);}));
 assert.deepEqual(errors,[]);assert(metrics.renderCpu.p95<20,'Desktop-hosted render regression');report.push({device,label,baselineRef:ref,loadMs,viewport,...metrics,errors});console.log(JSON.stringify(report.at(-1)));await c.close();
}fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify(report,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
